export * from './all/install';
export * from './and/install';
export * from './atLeastOne/install';
export * from './atMostOne/install';
export * from './compose/install';
export * from './curry/install';
export * from './exactlyN/install';
export * from './exactlyOne/install';
export * from './flip/install';
export * from './isFunction/install';
export * from './memoize/install';
export * from './not/install';
export * from './or/install';
export * from './parallel/install';
export * from './partial/install';
export * from './pipe/install';
export * from './retry/install';
export * from './sequence/install';
export * from './tap/install';
export * from './traverse/install';
export * from './uncurry/install';

import { installAll } from './all/install';
import { installAnd } from './and/install';
import { installAtLeastOne } from './atLeastOne/install';
import { installAtMostOne } from './atMostOne/install';
import { installCompose } from './compose/install';
import { installCurry } from './curry/install';
import { installExactlyN } from './exactlyN/install';
import { installExactlyOne } from './exactlyOne/install';
import { installFlip } from './flip/install';
import { installIsFunction } from './isFunction/install';
import { installMemoize } from './memoize/install';
import { installNot } from './not/install';
import { installOr } from './or/install';
import { installParallel } from './parallel/install';
import { installPartial } from './partial/install';
import { installPipe } from './pipe/install';
import { installRetry } from './retry/install';
import { installSequence } from './sequence/install';
import { installTap } from './tap/install';
import { installTraverse } from './traverse/install';
import { installUncurry } from './uncurry/install';

export function installFunctionExtensions() {
  installAll();
  installAnd();
  installAtLeastOne();
  installAtMostOne();
  installCompose();
  installCurry();
  installExactlyN();
  installExactlyOne();
  installFlip();
  installIsFunction();
  installMemoize();
  installNot();
  installOr();
  installParallel();
  installPartial();
  installPipe();
  installRetry();
  installSequence();
  installTap();
  installTraverse();
  installUncurry();
}
