export * from './aggregate/install';
export * from './avg/install';
export * from './avgAbsDevAroundMedian/install';
export * from './batch/install';
export * from './cartesianProduct/install';
export * from './chunk/install';
export * from './chunkWhile/install';
export * from './countBy/install';
export * from './crossJoin/install';
export * from './cumulativeAverage/install';
export * from './difference/install';
export * from './exponentialMovingAverage/install';
export * from './forItem/install';
export * from './forItemReverse/install';
export * from './fullJoin/install';
export * from './generalizedMean/install';
export * from './geometricMean/install';
export * from './groupBy/install';
export * from './harmonicMean/install';
export * from './innerJoin/install';
export * from './intersection/install';
export * from './leftJoin/install';
export * from './max/install';
export * from './meanAbsoluteDeviation/install';
export * from './median/install';
export * from './medianAbsoluteDeviation/install';
export * from './medianAbsoluteDeviationNormalized/install';
export * from './min/install';
export * from './move/install';
export * from './orderBy/install';
export * from './partition/install';
export * from './pluck/install';
export * from './product/install';
export * from './query/install';
export * from './rightJoin/install';
export * from './rootMeanSquare/install';
export * from './sample/install';
export * from './sampleSize/install';
export * from './shuffle/install';
export * from './simpleMovingAverage/install';
export * from './standardDeviation/install';
export * from './sum/install';
export * from './swap/install';
export * from './unique/install';
export * from './unzip/install';
export * from './variance/install';
export * from './weightedArithmeticMean/install';
export * from './weightedExponentialMovingAverage/install';
export * from './weightedGeneralizedMean/install';
export * from './weightedGeometricMean/install';
export * from './weightedHarmonicMean/install';
export * from './weightedMovingAverage/install';
export * from './weightedNormalizedMean/install';
export * from './weightedRootMeanSquare/install';
export * from './window/install';
export * from './zip/install';
export * from './zipWith/install';

import { installAggregate } from './aggregate/install';
import { installAvg } from './avg/install';
import { installAvgAbsDevAroundMedian } from './avgAbsDevAroundMedian/install';
import { installBatch } from './batch/install';
import { installCartesianProduct } from './cartesianProduct/install';
import { installChunk } from './chunk/install';
import { installChunkWhile } from './chunkWhile/install';
import { installCountBy } from './countBy/install';
import { installCrossJoin } from './crossJoin/install';
import { installCumulativeAverage } from './cumulativeAverage/install';
import { installDifference } from './difference/install';
import { installExponentialMovingAverage } from './exponentialMovingAverage/install';
import { installForItems } from './forItem/install';
import { installForItemsReverse } from './forItemReverse/install';
import { installFullJoin } from './fullJoin/install';
import { installGeneralizedMean } from './generalizedMean/install';
import { installGeometricMean } from './geometricMean/install';
import { installGroupBy } from './groupBy/install';
import { installHarmonicMean } from './harmonicMean/install';
import { installInnerJoin } from './innerJoin/install';
import { installIntersection } from './intersection/install';
import { installLeftJoin } from './leftJoin/install';
import { installMax } from './max/install';
import { installMeanAbsoluteDeviation } from './meanAbsoluteDeviation/install';
import { installMedian } from './median/install';
import { installMedianAbsoluteDeviation } from './medianAbsoluteDeviation/install';
import { installMedianAbsoluteDeviationNormalized } from './medianAbsoluteDeviationNormalized/install';
import { installMin } from './min/install';
import { installMove } from './move/install';
import { installOrderBy } from './orderBy/install';
import { installPartition } from './partition/install';
import { installPluck } from './pluck/install';
import { installProduct } from './product/install';
import { installQuery } from './query/install';
import { installRightJoin } from './rightJoin/install';
import { installRootMeanSquare } from './rootMeanSquare/install';
import { installSample } from './sample/install';
import { installSampleSize } from './sampleSize/install';
import { installShuffle } from './shuffle/install';
import { installSimpleMovingAverage } from './simpleMovingAverage/install';
import { installStandardDeviation } from './standardDeviation/install';
import { installSum } from './sum/install';
import { installSwap } from './swap/install';
import { installUnique } from './unique/install';
import { installUnzip } from './unzip/install';
import { installVariance } from './variance/install';
import { installWeightedArithmeticMean } from './weightedArithmeticMean/install';
import { installWeightedExponentialMovingAverage } from './weightedExponentialMovingAverage/install';
import { installWeightedGeneralizedMean } from './weightedGeneralizedMean/install';
import { installWeightedGeometricMean } from './weightedGeometricMean/install';
import { installWeightedHarmonicMean } from './weightedHarmonicMean/install';
import { installWeightedMovingAverage } from './weightedMovingAverage/install';
import { installWeightedNormalizedMean } from './weightedNormalizedMean/install';
import { installWeightedRootMeanSquare } from './weightedRootMeanSquare/install';
import { installWindow } from './window/install';
import { installZip } from './zip/install';
import { installZipWith } from './zipWith/install';

export function installArrayExtensions() {
  installAggregate();
  installAvg();
  installAvgAbsDevAroundMedian();
  installBatch();
  installCartesianProduct();
  installChunk();
  installChunkWhile();
  installCountBy();
  installCrossJoin();
  installCumulativeAverage();
  installDifference();
  installExponentialMovingAverage();
  installForItems();
  installForItemsReverse();
  installFullJoin();
  installGeneralizedMean();
  installGeometricMean();
  installGroupBy();
  installHarmonicMean();
  installInnerJoin();
  installIntersection();
  installLeftJoin();
  installMax();
  installMeanAbsoluteDeviation();
  installMedian();
  installMedianAbsoluteDeviation();
  installMedianAbsoluteDeviationNormalized();
  installMin();
  installMove();
  installOrderBy();
  installPartition();
  installPluck();
  installProduct();
  installQuery();
  installRightJoin();
  installRootMeanSquare();
  installSample();
  installSampleSize();
  installShuffle();
  installSimpleMovingAverage();
  installStandardDeviation();
  installSum();
  installSwap();
  installUnique();
  installUnzip();
  installVariance();
  installWeightedArithmeticMean();
  installWeightedExponentialMovingAverage();
  installWeightedGeneralizedMean();
  installWeightedGeometricMean();
  installWeightedHarmonicMean();
  installWeightedMovingAverage();
  installWeightedNormalizedMean();
  installWeightedRootMeanSquare();
  installWindow();
  installZip();
  installZipWith();
}
