export * from './avg/install';
export * from './batch/install';
export * from './cartesianProduct/install';
export * from './chunk/install';
export * from './chunkWhile/install';
export * from './countBy/install';
export * from './crossJoin/install';
export * from './difference/install';
export * from './forItem/install';
export * from './forItemReverse/install';
export * from './fullJoin/install';
export * from './groupBy/install';
export * from './innerJoin/install';
export * from './intersection/install';
export * from './leftJoin/install';
export * from './max/install';
export * from './min/install';
export * from './orderBy/install';
export * from './partition/install';
export * from './pluck/install';
export * from './product/install';
export * from './query/install';
export * from './rightJoin/install';
export * from './sample/install';
export * from './sampleSize/install';
export * from './shuffle/install';
export * from './sum/install';
export * from './unique/install';
export * from './unzip/install';
export * from './window/install';
export * from './zip/install';
export * from './zipWith/install';

import { installAvg } from './avg/install';
import { installBatch } from './batch/install';
import { installCartesianProduct } from './cartesianProduct/install';
import { installChunk } from './chunk/install';
import { installChunkWhile } from './chunkWhile/install';
import { installCountBy } from './countBy/install';
import { installCrossJoin } from './crossJoin/install';
import { installDifference } from './difference/install';
import { installForItems } from './forItem/install';
import { installForItemsReverse } from './forItemReverse/install';
import { installFullJoin } from './fullJoin/install';
import { installGroupBy } from './groupBy/install';
import { installInnerJoin } from './innerJoin/install';
import { installIntersection } from './intersection/install';
import { installLeftJoin } from './leftJoin/install';
import { installMax } from './max/install';
import { installMin } from './min/install';
import { installOrderBy } from './orderBy/install';
import { installPartition } from './partition/install';
import { installPluck } from './pluck/install';
import { installProduct } from './product/install';
import { installQuery } from './query/install';
import { installRightJoin } from './rightJoin/install';
import { installSample } from './sample/install';
import { installSampleSize } from './sampleSize/install';
import { installShuffle } from './shuffle/install';
import { installSum } from './sum/install';
import { installUnique } from './unique/install';
import { installUnzip } from './unzip/install';
import { installWindow } from './window/install';
import { installZip } from './zip/install';
import { installZipWith } from './zipWith/install';

export function installArrayExtensions() {
  installAvg();
  installBatch();
  installCartesianProduct();
  installChunk();
  installChunkWhile();
  installCountBy();
  installCrossJoin();
  installDifference();
  installForItems();
  installForItemsReverse();
  installFullJoin();
  installGroupBy();
  installInnerJoin();
  installIntersection();
  installLeftJoin();
  installMax();
  installMin();
  installOrderBy();
  installPartition();
  installPluck();
  installProduct();
  installQuery();
  installRightJoin();
  installSample();
  installSampleSize();
  installShuffle();
  installSum();
  installUnique();
  installUnzip();
  installWindow();
  installZip();
  installZipWith();
}
