export * from './abbreviate/install';
export * from './camelCase/install';
export * from './constantCase/install';
export * from './dotCase/install';
export * from './hamming/install';
export * from './initials/install';
export * from './isDateFormat/install';
export * from './isDuration/install';
export * from './isEmail/install';
export * from './isIPv4/install';
export * from './isIPv6/install';
export * from './isTime/install';
export * from './isURL/install';
export * from './isUUID/install';
export * from './jaro/install';
export * from './jaroWinkler/install';
export * from './kebabCase/install';
export * from './levenshtein/install';
export * from './lowerFirst/install';
export * from './moduleCase/install';
export * from './noCase/install';
export * from './pascalCase/install';
export * from './randomStr/install';
export * from './sentenceCase/install';
export * from './slugify/install';
export * from './snakeCase/install';
export * from './swapCase/install';
export * from './textPosition/install';
export * from './titleCase/install';
export * from './trainCase/install';
export * from './upperFirst/install';
export * from './words/install';

import { installAbbreviate } from './abbreviate/install';
import { installCamelCase } from './camelCase/install';
import { installConstantCase } from './constantCase/install';
import { installDotCase } from './dotCase/install';
import { installHamming } from './hamming/install';
import { installInitials } from './initials/install';
import { installIsDateFormat } from './isDateFormat/install';
import { installIsDuration } from './isDuration/install';
import { installIsEmail } from './isEmail/install';
import { installIsIPv4 } from './isIPv4/install';
import { installIsIPv6 } from './isIPv6/install';
import { installIsTime } from './isTime/install';
import { installIsURL } from './isURL/install';
import { installIsUUID } from './isUUID/install';
import { installJaro } from './jaro/install';
import { installJaroWinkler } from './jaroWinkler/install';
import { installKebabCase } from './kebabCase/install';
import { installLevenshtein } from './levenshtein/install';
import { installLowerFirst } from './lowerFirst/install';
import { installModuleCase } from './moduleCase/install';
import { installNoCase } from './noCase/install';
import { installPascalCase } from './pascalCase/install';
import { installRandomStr } from './randomStr/install';
import { installSentenceCase } from './sentenceCase/install';
import { installSlugify } from './slugify/install';
import { installSnakeCase } from './snakeCase/install';
import { installSwapCase } from './swapCase/install';
import { installTextPosition } from './textPosition/install';
import { installTitleCase } from './titleCase/install';
import { installTrainCase } from './trainCase/install';
import { installUpperFirst } from './upperFirst/install';
import { installWords } from './words/install';

export function installStringExtensions() {
  installAbbreviate();
  installCamelCase();
  installConstantCase();
  installDotCase();
  installHamming();
  installInitials();
  installIsDateFormat();
  installIsDuration();
  installIsEmail();
  installIsIPv4();
  installIsIPv6();
  installIsTime();
  installIsURL();
  installIsUUID();
  installJaro();
  installJaroWinkler();
  installKebabCase();
  installLevenshtein();
  installLowerFirst();
  installModuleCase();
  installNoCase();
  installPascalCase();
  installRandomStr();
  installSentenceCase();
  installSlugify();
  installSnakeCase();
  installSwapCase();
  installTextPosition();
  installTitleCase();
  installTrainCase();
  installUpperFirst();
  installWords();
}
