export * from './approximately/install';
export * from './clamp/install';
export * from './clerp180/install';
export * from './deltaAngle/install';
export * from './frac/install';
export * from './gcd/install';
export * from './lcm/install';
export * from './lerp/install';
export * from './lerpAngle/install';
export * from './mod/install';
export * from './moveTowards/install';
export * from './moveTowardsAngle/install';
export * from './pascalTriangle/install';
export * from './remap/install';
export * from './repeat/install';
export * from './roundToPointFive/install';
export * from './saturate/install';
export * from './toDegrees/install';
export * from './toRadians/install';
export * from './unlerp/install';

import { installApproximately } from './approximately/install';
import { installClamp } from './clamp/install';
import { installClerp180 } from './clerp180/install';
import { installDeltaAngle } from './deltaAngle/install';
import { installFrac } from './frac/install';
import { installGCD } from './gcd/install';
import { installLCM } from './lcm/install';
import { installLerp } from './lerp/install';
import { installLerpAngle } from './lerpAngle/install';
import { installMod } from './mod/install';
import { installMoveTowards } from './moveTowards/install';
import { installMoveTowardsAngle } from './moveTowardsAngle/install';
import { installPascalTriangle } from './pascalTriangle/install';
import { installRemap } from './remap/install';
import { installRepeat } from './repeat/install';
import { installRoundToPointFive } from './roundToPointFive/install';
import { installSaturate } from './saturate/install';
import { installToDegrees } from './toDegrees/install';
import { installToRadians } from './toRadians/install';
import { installUnlerp } from './unlerp/install';

export function installMathExtensions() {
  installApproximately();
  installClamp();
  installClerp180();
  installDeltaAngle();
  installFrac();
  installGCD();
  installLCM();
  installLerp();
  installLerpAngle();
  installMod();
  installMoveTowards();
  installMoveTowardsAngle();
  installPascalTriangle();
  installRemap();
  installRepeat();
  installRoundToPointFive();
  installSaturate();
  installToDegrees();
  installToRadians();
  installUnlerp();
}
